### ISSUE TITLE
[SOLUTIONS] Insights for setting up

### ISSUE THREAD

**Issue by gycka** [qijiezhao/py-denseflow#5]
I was setting this up in the end of August, 2019. Here are some findings that you need to do/change to make this work:

  - ```scipy.misc.imsave()``` has been [deprecated](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.misc.imsave.html) (in SciPy 1.0.0), instead, use ``` import imageio ``` and ``` imageio.imwrite() ```
  - ``` cv2.createOptFlow_DualTVL1() ``` did not work with opencv 4.X.X (pip install opencv-python). If installed this way, remove it (pip uninstall opencv-python) and install its different version (pip install opencv-contrib-python). Next, change ``` cv2.createOptFlow_DualTVL1() ``` to ``` dtvl1=cv2.optflow.DualTVL1OpticalFlow_create() ```
  - I had problems with the skvideo.io.vread() function. I had both ffmpeg/ffprobe installed using pip, but that did not work. I had success with [ conda install -c mrinaljain17 ffmpeg](https://anaconda.org/mrinaljain17/ffmpeg), but you can also install it from [source.](https://ffmpeg.org/)
  - As I had a different dataset setup than the author (I simply extracted UCF101 dataset, so my paths looked like this: ../../UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi, which I believe is the norm). Due to this, I had to remove the second argument for ``` os.path.join() ``` function found right after the main function and args = ... For example, the first line became ```data_root=os.path.join(args.data_root)```
  - If you are not parsing any arguments, change the default value for data_root. For example, ``` parser.add_argument('--data_root',default='../../Downloads/UCF-101',type=str)```

Hope this helps. Thank you for the scripts.

**Comment by sanolans** [comment]
Hi! I followed your solution but I'm getting the following error: NameError: name 'videos_root' is not defined. Did you encounter this error and how did you resolve it if you did?

Error details:
`runfile('D:/Clones/py-denseflow-master/denseflow1.py', wdir='D:/Clones/py-denseflow-master')
find 13320 videos.
get videos list done!
Traceback (most recent call last):

File "", line 1, in
runfile('D:/Clones/py-denseflow-master/denseflow1.py', wdir='D:/Clones/py-denseflow-master')

File "C:\Users\sancy\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
execfile(filename, namespace)

File "C:\Users\sancy\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)

File "D:/Clones/py-denseflow-master/denseflow1.py", line 184, in
pool.map(dense_flow,zip(video_list,flows_dirs,[step]*len(video_list),[bound]*len(video_list)))

File "C:\Users\sancy\Anaconda3\lib\multiprocessing\pool.py", line 290, in map
return self._map_async(func, iterable, mapstar, chunksize).get()

File "C:\Users\sancy\Anaconda3\lib\multiprocessing\pool.py", line 683, in get
raise self._value

NameError: name 'videos_root' is not defined`

**Comment by g2-bernotas** [comment]
@sanolans it seems that you somehow have deleted (?) videos_root variable. If you check the original code on this repository (denseflow.py) line 163 you will see that variable. I slightly modified it due to my set up, so it simply became:
``` Python
args=parse_args()
data_root=os.path.join(args.data_root)
videos_root=os.path.join(data_root)
```
If you need further help, please provide your main code (denseflow.py -> if __name__=='main'.

**Comment by sanolans** [comment]
Thanks for your work and for replying. I managed to resolve it by passing videos_root when calling the dense_flow  and the get_videos_list.See attached for full code.
However it appears that the code does not work for videos in .avi format, it is works for .mp4 formats. I am working with ucf101 dataset which is in .avi format, do you know of I way I can get around this issue?
Thanks in anticipation.    On Tuesday, September 24, 2019, 06:31:39 PM GMT+8, g2-bernotas <notifications@github.com> wrote:  
 
 
@sanolans it seems that you somehow have deleted (?) videos_root variable. If you check the original code on this repository (denseflow.py) line 163 you will see that variable. I slightly modified it due to my set up, so it simply became:
args=parse_args()
data_root=os.path.join(args.data_root)
videos_root=os.path.join(data_root)
If you need further help, please provide your main code (denseflow.py -> if name=='main'.

**Comment by sanolans** [comment]
Thanks for replying, its working now. However it stop after processing a number of videos, so I have to restart it.

**Comment by Malithi-gif** [comment]
Can anyone help me?
![image](https://user-images.githubusercontent.com/54534252/104718243-94c6f880-5750-11eb-904a-024be27cae73.png)

![image](https://user-images.githubusercontent.com/54534252/104718272-a1e3e780-5750-11eb-8562-7b6b24959a97.png)
