### ISSUE TITLE
NameError: name 'videos_root' is not defined

### ISSUE THREAD

**Issue by sanolans** [qijiezhao/py-denseflow#6]
Hello! very useful code. However when I run the code I get the above error. Do you know why that is and can I resolve it?

`runfile('D:/Clones/py-denseflow-master/denseflow1.py', wdir='D:/Clones/py-denseflow-master')
find 13320 videos.
get videos list done! 
Traceback (most recent call last):

  File "<ipython-input-7-d70e510efa56>", line 1, in <module>
    runfile('D:/Clones/py-denseflow-master/denseflow1.py', wdir='D:/Clones/py-denseflow-master')

  File "C:\Users\sancy\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\sancy\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Clones/py-denseflow-master/denseflow1.py", line 184, in <module>
    pool.map(dense_flow,zip(video_list,flows_dirs,[step]*len(video_list),[bound]*len(video_list)))

  File "C:\Users\sancy\Anaconda3\lib\multiprocessing\pool.py", line 290, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "C:\Users\sancy\Anaconda3\lib\multiprocessing\pool.py", line 683, in get
    raise self._value

NameError: name 'videos_root' is not defined`

**Comment by ghost** [comment]
Do you address that? I have the same error.
